set(_AMENT_PACKAGE_NAME "turtle_dancer")
set(turtle_dancer_VERSION "0.1.0")
set(turtle_dancer_MAINTAINER "Ruben Arts <ruben@prefix.dev>")
set(turtle_dancer_BUILD_DEPENDS "rclcpp" "geometry_msgs")
set(turtle_dancer_BUILDTOOL_DEPENDS "ament_cmake")
set(turtle_dancer_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs")
set(turtle_dancer_BUILDTOOL_EXPORT_DEPENDS )
set(turtle_dancer_EXEC_DEPENDS "turtlesim" "rclcpp" "geometry_msgs")
set(turtle_dancer_TEST_DEPENDS )
set(turtle_dancer_GROUP_DEPENDS )
set(turtle_dancer_MEMBER_OF_GROUPS )
set(turtle_dancer_DEPRECATED "")
set(turtle_dancer_EXPORT_TAGS)
list(APPEND turtle_dancer_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
